---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: berth-apiserver
rules:
- apiGroups:
  - berth.kubeberth.io
  resources:
  - archives
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - berth.kubeberth.io
  resources:
  - cloudinits
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - berth.kubeberth.io
  resources:
  - disks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - berth.kubeberth.io
  resources:
  - servers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: berth-apiserver
  namespace: kubeberth

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: berth-apiserver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: berth-apiserver
subjects:
- kind: ServiceAccount
  name: berth-apiserver
  namespace: kubeberth

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: berth-apiserver
  namespace: kubeberth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: berth-apiserver
  template:
    metadata:
      labels:
        app: berth-apiserver
    spec:
      serviceAccountName: berth-apiserver
      securityContext:
        runAsNonRoot: true
      containers:
      - name: berth-apiserver
        image: kubeberth/berth-apiserver:v1alpha1
        imagePullPolicy: Always
        ports:
        - containerPort: 2022
          name: berth-apiserver
          protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: berth-apiserver
  namespace: kubeberth
  annotations:
    external-dns.alpha.kubernetes.io/hostname: api.kubeberth.k8s.arpa
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - name: berth-apiserver
    protocol: TCP
    port: 80
    targetPort: 2022
  selector:
    app: berth-apiserver

---
